---
# tasks file for lamp
- name: LAMP installation
  include_vars: '{{ansible_os_family}}.yml'

- name: Debian
  apt: name={{item}} state=present
  with_items: '{{lamp_packages}}'
  when: ansible_os_family == "Debian"
  notify: 
    - starting and enabling apache
    - starting and enabling mariadb

- name: Centos
  yum: name={{item}} state=present
  with_items: '{{lamp_packages}}'
  when: ansible_os_family == "RedHat"
  notify: 
    - starting and enabling apache
    - starting and enabling mariadb
  
- name: désactiver les pare-feu de Centos
  shell: firewall-cmd --zone=public --permanent --add-service=http --add-service=https && firewall-cmd --reload
  when: ansible_os_family == 'RedHat'

- name: Mise en place de index.html
  template: 
    src: templates/index.j2
    dest: /var/www/html/index.html
    backup: yes
    owner: '{{apache_user}}' 
    group: '{{apache_user}}'
    mode: 0644 
